### ISSUE TITLE
Ошибка очереди .

### ISSUE THREAD

**Issue by mralexgon** [hronoas/SiteWatcher#1]
Ошибка обновления очереди, возможно это новая - не знаю предыдущей. Когда в очереди 1-2 сайта - работает норм, после добавления 3-го, во время наблюдения, при изменении наблюдаемого значения, возникает ошибка - "empty ... ". Если оставить тот же сайт 1 в очереди с теми же параметрами наблюдения - все ок, отслеживает норм без ошибок. 
   Просьба добавить звуковой сигнал при обнаружении изменений за наблюдаемым объектом - очень полезно, иногда нужно реагировать быстро, а все время   смотреть не получится...

**Comment by hronoas** [comment]
Не удалось воспроизвести ошибку. Уточните, порядок действий, чтобы её повторить.
Для выяснения причины, необходимо больше данных.
1. Какую версию SiteWatcher используете (указана в заголовке окна настроек)
2. Какие URL отслеживаете и какие элементы на странице выбираете
3. Какое именно "наблюдаемое значение" изменяете, и что это такое
4. Скриншот ошибки (предполагаю "empty result") и настройки наблюдателя

P.S. ошибка "empty result" возникает, когда не удалось найти отслеживаемый элемент на странице. Некоторые сайты могут блокировать доступ на время из-за частых обновлений страниц. Некоторые сайты требуют перехода с определенной страницы. В этих случаях на странице не будет отслеживаемого элемента.

**Comment by mralexgon** [comment]
Использовал предыдущую версию 0.9.1.4. Похоже, ошибка возникала тогда, когда программа отрпавляла запрос нескольким сайтам, Увеличил таймаут ожидания загрузки - пока ошибок нет, возможно в этом было дело. Спасибо за уведомления звуком! )
