### ISSUE TITLE
Первое уведомление нового наблюдателя

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#12]
ПОЖЕЛАНИЕ: Исключить самое первое уведомление об изменении на сайте, появляющегося после создания нового наблюдателя. Или, сделать возможность опционального включения/отключения такого уведомления на выбор. Ведь на практике в нём нету необходимости, поскольку на момент создания наблюдателя, известно, что отображено на сайте.

**Comment by hronoas** [comment]
Уведомление после первой проверки убрано в версии 0.9.2.4
