### ISSUE TITLE
Вставление адреса сайта из буфера обмена кнопкой

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#14]
ПОЖЕЛАНИЕ: Чтобы в строке "Адрес страницы" добавления нового наблюдателя, при нажатии кнопки в виде стрелки перехода на страницу, – программа вставляла бы адрес сайта из буфера обмена, если таковой там имеется заранее. Это было бы быстрее и удобнее, нежели чем нажимать правую кнопку мыши в строке, чтобы вызвать всплывающее меню для нажатия "Вставить" адрес из буфера обмена.

**Comment by hronoas** [comment]
Это неочевидное поведение. При знании горячих клавиш ctrl+v не должно возникать затруднений.
В версии 0.9.2.4 добавлено автоматическое открытие ПРАВИЛЬНОЙ ссылки из буфера обмена.
P.S. Такое поведение может компрометировать пользователя.
