### ISSUE TITLE
Название от краткого к полному

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#15]
ПОЖЕЛАНИЕ: Для окна добавления нового наблюдателя. Чтобы в строке "Название", программа по умолчанию вставляла бы краткое название. Однако при этом, чтобы у строки была бы кнопка выпадающего меню, в котором программой бы предлагалось несколько вариантов названий, от краткого до полного.

Например, если вставить адрес https://github.com/hronoas/SiteWatcher – то программа автоматически вставит полное название "GitHub - hronoas/SiteWatcher: Программа для автоматической проверки изменений на страницах сайтов".

Поэтому, согласно данному примеру было бы хорошо, чтобы по умолчанию вставлялось бы краткое название: "GitHub". Однако при этом, чтобы был и выпадающий список, при нажатии на которой, при желании можно было бы выбирать какой-либо другой вариант названия, от краткого до полного:
GitHub
hronoas
SiteWatcher
GitHub - hronoas
hronoas/SiteWatcher
GitHub - hronoas/SiteWatcher
Программа для автоматической проверки изменений на страницах сайтов
GitHub - hronoas/SiteWatcher: Программа для автоматической проверки изменений на страницах сайтов

**Comment by hronoas** [comment]
На текущий момент, вставляет заголовок страницы, чего достаточно в большинстве случаев.
Проще вручную удалить ненужную часть заголовка. В большинстве случаев проще и быстрее ввести заголовок, чем даже выбирать из списка предложений.
