### ISSUE TITLE
Внесения исключений

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#16]
ПОЖЕЛАНИЕ: Добавить возможность внесения исключений/игнорирования, чтобы программа не сигнализировала при наличии определённых слов в строке. Например, необходимо, чтобы программа сигнализировала при появлении слова "один". Но если оно появляется вместе со словом "три" в одной строке, предложении: "один два три", то в таком случае необходимо чтобы программа не сигнализировала.

**Comment by hronoas** [comment]
Этот функционал можно настроить через опцию "искать/заменить" в выбранных элементах.

**Comment by SWatB-com** [comment]
Можно ли пример?

**Comment by hronoas** [comment]
^((?!три).)*$ - не будет выводить ничего если присутствует слово "три" в содержимом

**Comment by SWatB-com** [comment]
СпасиБо..
В перспективе хорошо бы добавить в программу какие-нибудь готовые шаблоны такие, в инструкцю добавить подробности.
