### ISSUE TITLE
Кнопка переноса наблюдателей в прочтённые

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#17]
ПОЖЕЛАНИЕ: В кнопки главного меню добавить кнопку "Прочитано", чтобы её нажатием переносить все наблюдатели в статус прочтённых.

**Comment by hronoas** [comment]
Добавлено в версии 0.9.2.4

**Comment by SWatB-com** [comment]
Тоже хорошо.
Однако, мною имелось ввиду: добавить одну общую кнопку "Прочитаны все".
Там же, где кнопка "Проверить все".
Чтобы одним нажатием одной кнопки "переносить все наблюдатели в статус прочтённых".
