### ISSUE TITLE
Вписывание символов правым Alt

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#18]
ПОЖЕЛАНИЕ: Добавить возможность вписывания символов посредством правого Alt. По крайней мере, в версии 0.9.1.9 вписывание не происходит в окнах: "Выбирать" и "Искать/заменять".

**Comment by hronoas** [comment]
в версии 0.9.24 ввод через Alt работает во всех полях, где ввод возможен
