### ISSUE TITLE
Долго не обновляется статус "Ошибка"

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#19]
Иногда наблюдатель отмечается статусом "Ошибка", который держится слишком долго. По крайней мере, дольше, чем указана периодичность времени для проверки. Приходится самостоятельно нажимать на кнопку обновления.

ПОЖЕЛАНИЕ: Сделать, чтобы программа автоматически обновляла наблюдателя со статусом "Ошибка", в соответствии с указанным временем проверки. Без необходимости делать это вручную.

Как вариант, программе можно дать задачу постоянно обнаруживать и обновлять такие наблюдатели, независимо от заданного в них времени. И делать это поочерёдно, чтобы этим был занят лишь один процесс, иначе много обновлений за раз может сильно увеличить нагрузку.

**Comment by hronoas** [comment]
настройка "Проверка после ошибки через" будет в версии 0.9.2.4
