### ISSUE TITLE
Частота проверки сайта.

### ISSUE THREAD

**Issue by rndmfm** [hronoas/SiteWatcher#2]
Добрый день. Подскажите, а как изменить частоту проверки сайта? По умолчанию стоит 3ч и изменить нельзя.

**Comment by hronoas** [comment]
Добрый день.
Намудрил я там с проверкой значений )
1. Самое простое, отдельно выделить цифру и после этого вводить значение (число) или заменять букву (м, ч, д). 
2. Можно скопировать в буфер значение (например "10д") и заменить выделенный текст в поле "Проверка каждые"

**Comment by hronoas** [comment]
Исправлено в [v0.9.1.6](https://github.com/hronoas/SiteWatcher/releases/)
