### ISSUE TITLE
Сортировка в алфавитном порядке

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#20]
ПОЖЕЛАНИЕ: Добавить возможность сортировки наблюдателей в алфавитном порядке.

При большом количестве наблюдателей это позволит быстрее находить нужный. Или, наоборот, обнаруживать, что недостаёт ещё какого-то. А также, поможет избегать создания дубликатов.

**Comment by hronoas** [comment]
Для этого реализована возможность поиска путем ввода текста в поле с фильтром категорий.
Основная функция программы, следить за изменениями, поэтому сортировка именно по времени.

**Comment by SWatB-com** [comment]
А чего же в инструкции об этом не пояснено.
Даже не знал что можно искать.
Попробовал, понравилось, лучше чем ничего.
Даже страшно подумать, что там ещё сокрыто в программе, чего нету в инструкции.
