### ISSUE TITLE
Запоминание последнего введённого значения параметра "Проверка каждые"

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#21]
ПОЖЕЛАНИЕ: В настройках наблюдателя, параметр "Проверка каждые" сделать автоматически запоминаемым на последнее вводившееся значение. Чтобы, когда открываешь настройки наблюдателя, там стояло значение, которое вводилось при последнем создании. Это позволит не менять каждый раз стандартное значение "3ч" на какое-либо собственное.

**Comment by hronoas** [comment]
Для быстрой настройки наблюдателя, предусмотрена возможность дублирования (правой кнопкой мыши по существующему наблюдателю, затем "Дублировать"). Все настройки копируются с образца, после чего их можно изменить.

**Comment by SWatB-com** [comment]
Попробую, посмотрю как оно на практике.
