### ISSUE TITLE
Вкладки категорий

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#23]
ПОЖЕЛАНИЕ: Вместо текущего отображения категорий в виде раскрывающегося списка, сделать их отображение в виде вкладок. Примерно, как в браузере. При этом, как и в браузере, в конце вкладок можно разместить кнопку "+", чтобы по её нажатии добавлять новую вкладку категории.

**Comment by hronoas** [comment]
Предназначение SiteWatcher не подразумевает постоянное наблюдение за списком наблюдателей, он сам уведомляет об изменениях, это не браузер.
В большинстве случаев окно планировалось в свёрнутом состоянии.
Основное окно планировалось для быстрого обзора изменений, для этого есть группы и кнопка "new", вкладки усложнят внешний вид.
