### ISSUE TITLE
Перестало загружать сайт и выкидывает с ошибкой

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#25]
С версией 0.9.2.0 перестало автоматически загружать сайт, когда вставляешь ссылку в окно "Адрес страницы" и нажимаешь на какое-либо другое окно или место программы. Теперь приходится сначала нажимать на кнопку загрузки сайта.

А если вставить ссылку и нажать на кнопку "Запуск", то программа закрывается с отображением сообщения "Критическая ошибка".

**Comment by hronoas** [comment]
Изменился порядок загрузки страницы, теперь после вставки адреса или ввода ссылки вручную, необходимо нажать Enter или синюю стрелку вправо в поле "Адрес страницы".

Ошибку нашел. Будет исправлена в ближайшее время.

**Comment by SWatB-com** [comment]
На ряду с использованием Enter и стрелкой, предлагаю оставить атозагрузку.
Поскольку удобно.

**Comment by hronoas** [comment]
К сожалению, это вызывает много проблем. Ни один браузер не переходит на страницу при потере фокуса в адресной строке.

исправлено в [v0.9.2.1](https://github.com/hronoas/SiteWatcher/releases/tag/v0.9.2.1)
