### ISSUE TITLE
Закрывание кнопок неопределённой подсказкой наблюдателя

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#27]
ПОЖЕЛАНИЕ: Сделать, чтобы подсказка, всплывающая при наведении курсора на наблюдатель, всплывала под наблюдателем – по сути всплывая в определённом месте, а не под курсором – по сути всплывая где получится. Поскольку, всплывание под курсором иногда закрывает кнопки наблюдателя. А если бы всплывала лишь под наблюдателем, то кнопки оставались бы открытыми. Да и когда всплывает что-то в определённом месте, то оно лучше улавливается взглядом.

**Comment by hronoas** [comment]
Поправлено в [v0.9.2.3](https://github.com/hronoas/SiteWatcher/releases/tag/v0.9.2.3)
Но теперь подсказка закрывает нижний наблюдатель полностью, что тоже неудобно.

**Comment by SWatB-com** [comment]
Попробовал, так уже в любом случае лучше,
ПРЕДЛОЖЕНИЕ; Как вариант, попробовать сделать всплытие слева или справа окна.
Может, даже сделать опционально на выбор пользователю в настройках, какое всплытие больше нравится выставить: под курсором; под/над наблюдателем; справа окна; слева окна; вовсе без подсказки.

**Comment by hronoas** [comment]
Все варианты попробованы, снизу самый приемлемый. Пока делать что-то большее смысла нет.
