### ISSUE TITLE
Автосброс текста окна поиска

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#28]
ПОЖЕЛАНИЕ: Чтобы при нажатии на окно поиска наблюдателей выбора категорий, имеющийся там текст автоматически сбрасывался бы, для возможности написания собственного искомого текста. Иначе, имеющийся там текст приходится каждый раз удалять самостоятельно.

**Comment by hronoas** [comment]
Текст необходим для предотвращения срабатывания фильтра при случайных кликах по полю выбора категорий. Без начала ввода отображаются наблюдатели по фильтру выбранных категорий.

**Comment by SWatB-com** [comment]
Но чтобы нам пользоваться поиском в окне выбора категорий, всё равно же сначала приходится имеющийся там текст удалять вручную, чтобы написать свой. Так почему бы не сделать так, чтобы текст удалялся автоматически, когда мы собираемся ввести там свой поисковый текст.

Впрочем, если так сделать неприемлемо, то как вариант, предлагаю сделать, чтобы программа текст не удаляла, а хотя бы выделяла. Тогда он сам бы удалялся при нашем начале ввода собственного поискового текста. Для данного пожелания мною создано отдельное Issues.
