### ISSUE TITLE
Кнопка "Дублировать"

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#29]
ПОЖЕЛАНИЕ: В главном меню добавить наблюдателям кнопку "Дублировать".

**Comment by hronoas** [comment]
Будет в версии 0.9.2.5

**Comment by SWatB-com** [comment]
Проверил версию 0.9.2.5 – у меня кнопки "Дублировать" там почему-то не отображено.

**Comment by SWatB-com** [comment]
Проверил и обнаружил что решение вышло неожиданным.
Думал, кнопка дубляжа будет отображена у каждого наблюдателя, а она выведена отдельно.

Но как же в таком случае другие кнопки в наблюдателях?
Ведь, они тоже могли бы быть выведены отдельно.
То есть, должен же быть наверное какой-то единый функциональный стиль.

Либо: каждому наблюдателю свою кнопку, для нажатия там же – что функцианирует быстрее/удобнее, но занимает больше места в каждом наблюдателе.
Либо: вывод всех кнопок отдельно, чтобы сначала выбирать наблюдатель, а затем нажимать кнопку – что менее удобно, но не требует места в каждом наблюдателе.

Либо удобство, либо место.
Удобство наверное приоритетней, тем более, с панелью кнопок в наблюдателях можно ещё что-то придумать.

Как вариант: сделать её всплывающей вместе с подсказкой – между наблюдателем и самой подсказкой.
Либо конкретно разместить постоянную панель под каждым наблюдателем, с текущими кнопками и возможными будущими, сделав наблюдатели выше.

Или экран сделать шире, и соотвественно шире сделать наблюдатели, разместив панель сбоку.
Ведь это компьютерная версия программы.
Лично мне сразу же показалось мало, что окно узкое и нету возможности менять ширину.

**Comment by hronoas** [comment]
Верхняя панель содержит "глобальные" кнопки, которые не могут быть размещены в каком-то конкретном наблюдателе или его контекстном меню (ну по крайней мере так было). Копку дублировать туда вынес, т.к. в наблюдателе нет под нее нет места и функцией она схожа с кнопкой добавить.
Также в "удобство" входит внешний вид программы ("место"), поэтому не стоит перегружать интерфейс.
Вообще, планировались изменяемые размеры окна, но это добавляет много возни с нехваткой места для элементов при слишком маленьких размерах окна. Возможно в будущем, когда-нибудь, когда дойдет до необходимости переделать дизайн, всё реорганизуется (это же касается темной темы), но пока не планируются глобальные изменения.

**Comment by SWatB-com** [comment]
Обнаружил, что, при первом запуске 0.9.2.6 кнопки дублирования нету.
Она появлятся если выбрать наблюдатель.
Так не должно быть?

**Comment by hronoas** [comment]
Без выделенного наблюдателя кнопка не отображается.
