### ISSUE TITLE
Подчёркивание заголовка

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#30]
ПОЖЕЛАНИЕ: У наблюдателей убрать подчёркивание заголовка. Поскольку без него восприятие символов лучше. И должно быть достаточным, что, заголовок большого размера, жирного шрифта, и стрелка мыши реагирует на его наведение.

**Comment by hronoas** [comment]
Элемент не воспринимается как нажимаемый (без наведения мыши) без подчеркивания.
