### ISSUE TITLE
Быстрое переименование наблюдателя

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#32]
Добавить возможность быстрого переименования наблюдателя, прямо из главного меню. Делая это каким-либо из вариантов:
• Удерживающим нажатием левой кнопкой мыши на названии, чтобы оно перешло в режим переименования. Не требуется место для кнопки, но менее очевидно.
• Добавлением кнопки "Переименовать". Требуется место для кнопки, но зато быстро и очевидно.
• Добавлением соответствующей команды во всплывающем меню, вызываемого правым нажатием мышью. Требуется дополнительное действие, в качестве нажатия правой кнопкой мыши.

**Comment by hronoas** [comment]
На мой взгляд элементы не должны менять поведения при одинаковых действиях (удерживание левой кнопки) - это добавит неправильных срабатываний (для примера, на сенсорных экранах, долгое удерживание вызывает правый клик)
В списке наблюдателей уже присутствует функция редактирования (кнопка редактирования).
