### ISSUE TITLE
Автоматические категории по доменам

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#33]
Добавить возможность, чтобы программа автоматически могла отображать наблюдатели определённой категорией, с учётом их отношения к тому или иному домену. Например, если имеется множество наблюдателей с ссылкой домена "github.com", то чтобы она отображала соответствующую категорию: наблюдатели относящиеся к "github.com". Чтобы не самим создавать такого рода категорий по доменам.

**Comment by hronoas** [comment]
1. Можно добавить необходимую категорию в список и выбрать её как фильтр.
2. Если ввести в поле фильтра категорий "github" - выведется список наблюдателей с гитхаба, поиск происходит по ссылке и названию наблюдателя.
3. Необходимо сохранить вид главного окна как можно более простым, для удобства. Добавление дополнительных элементов управления будет затруднять его восприятие.
