### ISSUE TITLE
Автовыделение текста окна поиска

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#34]
!!! Ранее было похожее пожелание, касавшееся автоудаления текста (что оказалось неприемлемым), но на этот раз, пожелание касается автовыделения (надеюсь такой вариант будет приемлемой альтернативой).

Добавить возможность, чтобы при нажатии на окно поиска наблюдателей выбора категорий, имеющийся там текст автоматически выделялся бы, для возможности написания там собственного искомого текста. В таком случае, выделяемый текст удалится, когда мы будем вводить собственный искомый текст. А иначе, имеющийся там текст приходится каждый раз выделять, чтобы удалять самостоятельно.

**Comment by hronoas** [comment]
При первом клике по полю (при получении фокуса) с фильтрами весь текст выделяется, можно сразу начинать ввод.
