### ISSUE TITLE
Кнопка свёртывания

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#35]
У кнопки свёртывания программы, внизу правее отсутствует фрагмент.
И выглядит она крестообразно, что обычно подразумевает функцию – закрытия программы.
Хотя для свёртывания обычно используется символ в виде полосы.

**Comment by hronoas** [comment]
Пользователю проще понять (мне так кажется), что делает крест, нежели объяснить "что это за палочка" и почему нет кнопки закрыть, плюс стандартное для windows расположение на месте кнопки закрыть.

**Comment by SWatB-com** [comment]
Не настаиваю.

Как вариант, можно изобразить комбинацию: круг убрать, оставив крестовидность, под которую разместить полосу/палочку.
