### ISSUE TITLE
Приемлемость отсутствующего элемента

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#37]
Правильно ли понимаю, что, если в наблюдателе прописать контейнерный элемент, который при этом будет отсутствовать на сайте, то наблюдатель посчитает такое ошибкой?

Дело в том, что, некоторые сайты отображают или убирают контейнерные элементы лишь при наличии или отсутствии информации. В таких случаях, остаётся лишь просто ждать, когда появится контейнер с информацией. Что, наблюдателем не должно считаться ошибкой.

Если понял правильно, то предлагаю это как-то решить.
Как вариант, для такого рода сайтов добавить в наблюдатели опцию, включённость которой не считала бы ошибкой отсутствие контейнера. И соответственно, не ненужно было бы лишний раз задействовать опцию "при ошибках проверять каждые", и нагружать процесс с процессором.

**Comment by hronoas** [comment]
Для исключения ошибки можно:
1. Выбрать вторым элементом отслеживания любой пустой элемент или замещающий элемент, когда нет содержимого.
2. Выбрать для отслеживания элемент выше по структуре DOM дерева, который всегда существует, пусть и пустой.
