### ISSUE TITLE
Переходить со страницы (Referer)

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#38]
Для чего это может быть полезно? (А то одробности в инструкции не обнаружил) — 
Опция: «Переходить со страницы (Referer)»
Пояснение: «"Перед загрузкой страницы для проверки, будет загружена страница адрес, которой указан в этом
поле, и будет осуществлен переход на страницу, адрес которой указан в поле "Адрес страницы"»

Кстати, в тексте: "будет загружена страница адрес, которой указан в этом
поле" – запятая наверное необходима в другом месте: "будет загружена страница, адрес которой указан в этом
поле".

**Comment by hronoas** [comment]
Любой поисковик первым запросом выдает, зачем нужен Referer.
Добавлю только, что есть сайты, которые не дают напрямую получить страницу, им обязательно нужно, чтобы на страницу перешли с их сайта или другого определенного.
