### ISSUE TITLE
Кнопочное перебрасывание вниз и вверх списка наблюдателей

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#39]
Добавить кнопочную возможность перебрасывания сразу в самый низ списка наблюдателей, и обратно в самый вверх. При этом, необязательно добавлять две кнопки – вниз и вверх. Достаточно одной, поочерёдные нажатия на которую могли бы перебрасывать сразу вниз и обратно вверх.

**Comment by hronoas** [comment]
Сортировка в списке происходит по последнему времени изменения содержимого отслеживаемой страницы.

**Comment by SWatB-com** [comment]
Имею ввиду другое.
Поясню: справа окна есть ползунок, чтобы с помощью него перемещаться верх или вниз списка.
И вот помимо этого ползунка, предлагаю добавить кнопчную возможность перемещения.
Которая перемещала бы сразу резко в самый низ или вверх – это быстрее и удобнее, если нужно быстро переместится вниз или вверх.

**Comment by hronoas** [comment]
при фокусе на списке работают кнопки PageUp, PageDown, Home и End
