### ISSUE TITLE
СпасиБо.. за программу

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#4]
СпасиБо.. за программу.
Неожиданная, весьма хорошая и нужная.

Предлагаю заимствовать в неё лучшее, что есть как минимум в двух лучших браузерных расширениях: WebMonitor https://wm.suluf.com/ и Distill Web Monitor https://distill.io/

Лично мне хватает возможности указать перечень слов – каждое слово в отдельности, на коорые программа могла бы реагировать, если бы такие слова появлялись на странице. Насколько понимаю, сейчас можно лишь прописывать перечень слов единым списком?

**Comment by hronoas** [comment]
Спасибо за отзыв.

Программа писалась как замена distill, "облегченная" версия, чтобы не держать браузер открытым, не пользоваться платной версией и т.д.

Для отслеживания изменения текста (csv, json, xml и т.д.), можно воспользоваться регулярными выражениями (поиск по тексту, например html) в настройках наблюдателя.

Например, отслеживание курса валют на яндексе:
![image](https://github.com/hronoas/SiteWatcher/assets/13671811/c6e970bf-554d-4734-a664-f51da131e275)

**Comment by SWatB-com** [comment]
WebMonitor на мой взгляд более функциональней чем Distill.

А Regex – сложноватая штука. Лично мне мало что там понятно, хотя опыт пользования есть. Что уж говорить об обычных смертных. Было бы хорошо дополнительно к нему иметь возможность пользоваться чем-то интуитивно более понятным, шаблонным.

**Comment by SWatB-com** [comment]
Правильно ли понимаю, что для сигнала, при наличии например слов: раз, два, три, – необходимо внести код: "раз|два|три"?

**Comment by hronoas** [comment]
Да верно.

Единственное, что может стоит добавить дополнительно какое-то выражение например (раз|два|три)**([^<]*)** , 
иначе реакция на изменения будет только при появлении или пропадании слова. 
С дополнением же будет реагировать на изменение строки после слова и до следующего html тега (тут надо настраивать в зависимости от отслеживаемого содержимого страницы)

**Comment by SWatB-com** [comment]
Работает!
Пребываю в восторге.
Даже отключил второй браузер, на котором работало расширене.
Теперь буду пользоваться программой.

А для каждого пожелания или сообщения об ошибках, тут необходидмо создаваать отдельную тему каждый раз, или можно всё в одной теме оставлять?

**Comment by hronoas** [comment]
Для каждого необходимо создавать отдельный issues.
