### ISSUE TITLE
Уведомление о старых изменениях

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#40]
Если включить старый наблюдатель, чтобы отслеживать новые изменения, то прежде этого, он может выдать уведомление о старых изменениях. Накопившихся с момента отключения, если таковые там действительно накопились.

Лично в моей практике, в такого рода уведомлений нету нужды, ожидая лишь уведомлений о новых изменениях. Предлагаю это как-то решить.

Например, для старых включаемых наблюдателей, отключить уведомление об изменениях, накопившихся за то время что наблюдатель был отключён.

Или, добавить в наблюдатели включаемую/отключаемую опцию: после включения наблюдателя, не уведомлять о накопившихся изменениях в период его неактивности. Чтобы пользователь сам мог решать, нужны ли ему подобного рода уведомления в том или ином наблюдателе.

**Comment by hronoas** [comment]
Логика уведомлений предполагает наличие предыдущего изменения в данных наблюдения. При отключенном наблюдателе данные об изменениях не обновляются, и при включении наблюдателя появляются новые данные, и вызывается уведомление. Включение наблюдателя может (чаще всего так) происходить без просмотра отслуживаемой страницы, и получение уведомления об изменении скорее полезно, чем неудобно.
Также маловероятно многократное выключение и включение наблюдателей в коротком периоде.
