### ISSUE TITLE
Открытие нескольких ссылок наблюдателей разом

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#41]
Насколько понимаю, в текущей версии можно открывать лишь по одной ссылке наблюдателей за раз, нажимая на названии наблюдателей поочерёдно. Нету возможности открывать несколько ссылок наблюдателей одним разом.

ПОЖЕЛАНИЕ: В меню наблюдателя, всплывающее при нажатии правой кнопкой мыши, добавить команду, которая открывала бы ссылку наблюдателя. Чтобы одним разом можно было открывать ссылки нескольких заранее выделенных наблюдателей.

**Comment by hronoas** [comment]
добавлено в v0.9.2.9
