### ISSUE TITLE
Быстрое включение/отключение наблюдателей

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#43]
После нажатия кнопки включения/отключения наблюдателя, программа какое-то время сначала совершает некие внутренние процессы по включению/отключению, прежде чем отобразит это визуально.

ПОЖЕЛАНИЕ: Чтобы программа сначала включала/отключала наблюдатель визуально, и только затем совершала бы соответствующие внутренние процессы. Это позволило бы быстро включать/отключать наблюдатели хотя бы визуально, без ожидания, когда программа исполнит включение/отключение уже на своём внутреннем уровне.

**Comment by hronoas** [comment]
реализовано в версии 0.9.3.1
