### ISSUE TITLE
Положение активных наблюдателей

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#44]
Создаваемые активные наблюдатели иногда размещаются где-то внизу списка, среди неактивных наблюдателей. А не вверху, среди наблюдателей активных. Так не должно быть? Активные же вроде бы должны быть в приоритете – выше неактивных.

**Comment by hronoas** [comment]
в версии 0.9.2.9 улучшена сортировка: активные сверху, неактивные снизу и также сортируются по времени
