### ISSUE TITLE
[Улучшение]: Временные интервалы проверки обновления сайт

### ISSUE THREAD

**Issue by debobrov** [hronoas/SiteWatcher#47]
Не понятно какие интервалы проверки сайтов можно использовать в программе, в лучшем случае 3ч можно поменять на 1ч, но можно ли поставить минуты и в каких единицах прописать - не известно.
Было бы не плохо или дополнение в описании добавить, или сделать выпадающее окошко с временными интервалами.

**Comment by hronoas** [comment]
при наведении курсора мыши на поле со временем, всплывает подсказка с примерами заполнения
