### ISSUE TITLE
[Ошибка]: Не проходит проверку Cloudlfare

### ISSUE THREAD

**Issue by naemNik300** [hronoas/SiteWatcher#49]
### Перед отправкой описания ошибки убедитель, что выполнили эти инструкции

- [X] Прочитать [инструкцию](https://github.com/hronoas/SiteWatcher/blob/main/manual/SiteWatcher_GUI_desc.pdf)
- [X] Убедиться, что в системе установлены все, необходимые для запуска программы, [компоненты](https://github.com/hronoas/SiteWatcher#минимальные-системные-требования-для-запуска)
- [X] Убедиться, что ошибка повторяется

### Описание ошибки

```Markdown
Здравствуйте, браузер SiteWatcher перестал проходить проверку Cloudflare. При проверки в главном окне выдает ошибку, если нажать редактировать, чтобы перейти в браузер программы, то появляется окно с клаудом и его капчей. В обычном браузере, например хроме, проверка проходит без проблем. В SiteWatcher капча постоянно крутится и выбивает ошибку, и так можно бесконечно нажимать проверить, он не хочет в итоге переходить на нужную страницу, мешает клауд.

Прикрепил скриншот с ошибкой
```

### Воспроизведение ошибки

![Без имени](https://github.com/hronoas/SiteWatcher/assets/169096719/f59e0c10-51a1-41f2-9da9-1fa6d5df722c)

### Ожидаемое поведение

Ожидалось: ...
Произошло: ...

**Comment by hronoas** [comment]
Внезапно cloudflare перестал работать на старых версиях CefSharp 
исправлено в версии v0.9.3.1, CefSharp обновлен до версии 124.3.20, что привело к прекращению поддержки работы SiteWatcher в Window 7, 8, 8.1
