### ISSUE TITLE
Уведомления лишь при появлении слов

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#5]
В текущей версии программы, она уведомляет о появлении и исчезновении определённых слов на странице, заранее заданных для отслеживания.

ПОЖЕЛАНИЕ: Добавить возможность уведомлений только лишь при появлении таких слов.

**Comment by hronoas** [comment]
Этот функционал можно настроить через опцию "искать/заменить" в выбранных элементах.

**Comment by SWatB-com** [comment]
Каким образом?
Нужен какой-то код?
Можно ли пример?

**Comment by hronoas** [comment]
Пример (самый простой):
Если в "Искать/Заменить" в "Regex Filter" указать строку "машина", уведомление будет появляться при появлении слова "машина" в отслеживаемом элементе и при пропадании слова из элемента.
При помощи regex можно также преобразовывать данные из одного вида в другой.

**Comment by SWatB-com** [comment]
Это было понятно, но как же сделать, чтобы небыло уведомлений при пропадании слов?
Ведь нужно, чтобы были "Уведомления лишь при появлении слов".
