### ISSUE TITLE
Исключение множества начальных поочерёдных уведомлений

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#6]
В текущей версии программы, если наблюдателей много, и при этом программа только запустилась; или уже была запущена, но был произведён выход из спящего режима; или было произведено подключение интернета; – то в таком случае может оказаться много наблюдателей с новой информацией. И тогда программа запускает множество поочерёдных уведомлений, одно за другим.

ПОЖЕЛАНИЕ: Как-то исключить или минимизировать подобное, поскольку, когда всё только запускается, и без того понятно, что накопилось много нового. В таком случае всё равно приходится заглядывать в программу без необходимости в начальном множестве уведомлений. Уведомления необходимы лишь при дальнейшем использовании программы, когда она уже была запущена и все наблюдатели в ней просмотрены.

В качестве варианта решения, например, пусть программа делает лишь одно общее уведомление, если за раз накапливается много наблюдателей с новой информацией, когда программа только начинает свою активность при запуске, или после выхода компьютера из спящего режима, или по включении интернета.

**Comment by hronoas** [comment]
Уведомления можно отключить в настройках наблюдателя, раз они не важны, иначе можно пропустить произошедшие обновления после запуска.
