### ISSUE TITLE
Автообнаружение новых версий

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#8]
ПОЖЕЛАНИЕ: Добавить автоматическое обнаружение новых версий программы. Желательно с возможностью выбора: чтобы программа уведомляла о об этом, или чтобы автоматически обновлялась в тихом режиме – без уведомлений.

**Comment by hronoas** [comment]
из-за выбора "упрощенной" архитектуры приложения слишком накладно
не планируется
вариант решения: настроить наблюдатель:
```
url: https://github.com/hronoas/SiteWatcher/releases
xpath: (//div[contains(@class,"Box-body")])[1]
```
