### ISSUE TITLE
Прекращение всплывающих уведомлений после спящего режима

### ISSUE THREAD

**Issue by SWatB-com** [hronoas/SiteWatcher#9]
ПРОБЛЕМА: После вывода компьютера из спящего режима, программа иногда перестаёт показывать всплывающие уведомления.

**Comment by hronoas** [comment]
Что подразумевается под "спящим режимом"? Гибернация или спящий режим по таймеру?

**Comment by SWatB-com** [comment]
Гибернация.

**Comment by hronoas** [comment]
если есть возможность, надо проверить версию [0.9.2.6](https://github.com/hronoas/SiteWatcher/releases/tag/v0.9.2.6)
там изменен таймер, может это устранит проблему

**Comment by SWatB-com** [comment]
Погоняю, посмотрю как поведёт.

**Comment by SWatB-com** [comment]
Сходу заметил, что, пропала кнопка дублирования, и в опциях пропала возможность выставлять время проверки ошибочных наблюдателей.
